### ISSUE TITLE
Is the python API stable?

### ISSUE THREAD

**Issue by seanmacavaney** [ireval/cwl#18]
This is a really nice tool. I'm interested in adding it to the [ir_measures](https://ir-measur.es/) package ([issue](https://github.com/terrierteam/ir_measures/issues/21)), which would add support for the C/W/L measures to pyterrier and other tools.

All the examples provided use the command line interface. I could use this (by calling [main](https://github.com/ireval/cwl/blob/master/cwl/cwl_eval.py#L99) and capturing stdout), but it would probably be more convenient and faster to use the internal (and undocumented) python API that's already in the tool. Can I trust that the python API is stable and unlikely to change in major ways in future versions?

Thanks!

**Comment by leifos** [comment]
Oh nice. That would be very CWL :-)

We aren't planning to change the API - it does make sense to use it directly. As going through the CLI is clunky.

**Comment by seanmacavaney** [comment]
Awesome - very CWL! Thanks
