### ISSUE TITLE
differences with trec_eval in nDCG@k calculation

### ISSUE THREAD

**Issue by seanmacavaney** [ireval/cwl#20]
I noticed that there can be some differences between the nDCG@k scores calculated by trec_eval and those from cwl_eval. See below:

```bash
curl https://ir.nist.gov/covidSubmit/data/qrels-rnd2.txt > qrels
curl https://ir.nist.gov/covidSubmit/archive/round2/GUIR_S2_run1 > run

trec_eval qrels run -m ndcg_cut.10 -q | awk '$2>10 && $2<15'
# ndcg_cut_10           	11	0.2196
# ndcg_cut_10           	12	0.5767
# ndcg_cut_10           	13	0.4842
# ndcg_cut_10           	14	0.6286

echo "NDCGCWLMetric(10)" > ndcg10.txt
cwl-eval qrels run -m ndcg10.txt  --max_gain 2 | awk '$1>10 && $1<15'
# 11	NDCG-k@10	0.2680	1.2176	1.0000	4.5436	4.5436
# 12	NDCG-k@10	1.1533	5.2403	1.0000	4.5436	4.5436
# 13	NDCG-k@10	0.9684	4.3999	1.0000	4.5436	4.5436
# 14	NDCG-k@10	1.2572	5.7124	1.0000	4.5436	4.5436
```

These are ~double because the max gain is 2. We can re-scale the gains fractionally to fix this:

```bash
awk '$4==1 {$4=0.5} $4==2 {$4=1} {print}' qrels > qrels.scaled
cwl-eval qrels.scaled run -m ndcg.metricsfile | awk '$1>10 && $1<15'
# 11	NDCG-k@10	0.1340	0.6088	1.0000	4.5436	4.5436  # <- 0.1340 != 0.2196
# 12	NDCG-k@10	0.5767	2.6201	1.0000	4.5436	4.5436
# 13	NDCG-k@10	0.4842	2.1999	1.0000	4.5436	4.5436
# 14	NDCG-k@10	0.6286	2.8562	1.0000	4.5436	4.5436
```

The scores now all now match trec_eval except topic 11. Unlike most topics in this collection, it has few rel=2 judgments:

```bash
awk '$1==11{print $4}' qrels | sort | uniq -c
# 397 0
#  23 1
#   1 2
```

If we add more rel=2 qrels, it fixes the discrepancy:

```bash
cp qrels qrels.add
for i in {1..10} ; do echo "11 0 fakedoc-$i 2" >> qrels.add ; done
trec_eval qrels.add run -m ndcg_cut.10 -q | awk '$2>10 && $2<15'
# ndcg_cut_10           	11	0.1340 # <- now matches cwl-eval
# ndcg_cut_10           	12	0.5767
# ndcg_cut_10           	13	0.4842
# ndcg_cut_10           	14	0.6286
```

Are these differences between the C/W/L version of nDCG and the trec_eval version intentional? From my understanding of this area, they are because trec_eval's implementation assumes that all relevant documents in the collection are known and calculates its IDCG value accounting for this (i.e., only using 1 rel=2 judgment, in the example above), rather than the C/W/L approach of acknowledging that additional highly-relevant documents likely exist and calculating IDCG on that premise. But I want to be sure that my understanding is correct.

Thanks,
sean

**Comment by leifos** [comment]
Technically in CWL it is scaled DCG - so it doesn't explicitly normalise with respect the Ideal DCG but implicitly through the CWL there is normalization that makes it equivalent under certain conditions. However, there may be edge cases like in topic 11. 

On the gain / rel issue. Since CWL doesn't normalise explicitly with respect to an ideal, you can get expected utility values greater than one. This is intention because if your units of gain were say in dollars $$ or nuumber of nuggets, then they could be bigger than one. So you're work around of normalizing the gain (rels) before hand is a way to deal with this.

I think it would be good if we could talk to go over these.

**Comment by seanmacavaney** [comment]
I see - this makes a lot of sense. Just emailed your ACM address to schedule a chat about this.

**Comment by seanmacavaney** [comment]
Conclusion from today's meeting: rename NDCG in this software to SDCG (scaled NDCG) to avoid confusion.

**Comment by leifos** [comment]
I've updated the metrics to now output sDCG to avoid confusion with it being considered as nDCG. 

Also, I updated the readme file to note down the caveats of use gain files (as opposed to relevance judgements) as input.
