### ISSUE TITLE
"Qrels" files should accept floats?

### ISSUE THREAD

**Issue by JMMackenzie** [ireval/cwl#8]
Firstly, thanks for the great tool! 

I am trying to work with pre-computed gains for graded relevance. As far as I am aware, I should be able to pass in "qrels" files with floating-point gain values (rather than integer qrels). That is, instead of having qrels with 0/1/2/3/4, I could use values like 0 / 0.0625 / 0.125 / ...

Is that correct?

If so, I think there's a bug here: https://github.com/ireval/cwl/blob/master/cwl/seeker/topic_document_file_handler.py#L68

In particular, casting the judgement to an integer will mean that the tool works only for integer qrels files. If I have misunderstood, please close this issue :-)

**Comment by leifos** [comment]
Thanks Joel, I've updated this to type cast as a float instead of an int.
